### PR TITLE
Java 8 version

### PR DESCRIPTION
**Pull request by spullara**
Ported to Java 8 stream API.

### CODE REVIEW

**Comment by jmoy** [comment]
Thanks. This will be a valuable addition indeed. But to fit in with the rest of the programs so that this too can be easily tested and benchmarked can you please make the following changes:
1. The program should read from standard input (which might be redirected to a file) and produce output on standard output. 
2. The output should be lines of the form `word, correction` where `correction` is the single best correction and not a list.
3. The build should produce a single executable jar.

**Comment by spullara** [comment]
I think that it now meets those requirements.

**Comment by spullara** [comment]
Can run the mk_benchmark but I must have made a mistake in the port. Will re-comment when it passes with 0 diffs.

**Comment by spullara** [comment]
Ok, should be good to go. Runs with 0 diffs.

```
./util/mk_benchmark java/target/appassembler/bin/spellcheck

### java/target/appassembler/bin/spellcheck

    /usr/bin/time java/target/appassembler/bin/spellcheck data/train.txt </dev/null

        0.78 real         1.37 user         0.10 sys

    /usr/bin/time java/target/appassembler/bin/spellcheck data/train.txt <data/test.txt >OUTFILE

        5.10 real         6.08 user         0.37 sys

    diff -U0 OUTFILE data/output.txt|wc -l

       0
```

**Comment by jmoy** [comment]
Thanks. Have merged it with some changes to fit it into the existing build system.

**Pull request merged**
